#!/bin/sh

# script/builds - builds the release

# exit on sub-module failure
set -e

cd "$(dirname "$0")/.."

# ------

echo "Publishing Docker Hub..."
echo "$(dirname "$0")/.."

docker build -t currency-calculator ./
docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
docker tag currency-calculator $DOCKER_USER/currency-calculator:latest
docker push $DOCKER_USER/currency-calculator

echo "Done publishing!"

# ------
